services:
  ubuntu1:
    image: ubuntu:22.04
    hostname: ubuntu1
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: on-failure
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      localnet:
        ipv4_address: 192.168.1.197

  ubuntu2:
    build: ./ubuntu
    hostname: ubuntu2
    restart: on-failure
    stdin_open: true # docker run -i
    tty: true        # docker run -t
    networks:
      localnet:
        ipv4_address: 192.168.1.198      
    
networks:
  localnet: 
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.1.192/28
